export const questionsOfTheGame = [
    {questionText : "Who is best player",
    option1 : "Messi",
    option2: "Ronaldo",
    option3 : "Rahim",
    option4 : "Gori",
    correctAnswer : "Messi"},

    {questionText : "Who is world cup winner 2010",
    option1 : "Spain",
    option2: "Italy",
    option3 : "Germany",
    option4 : "Netherlands",
    correctAnswer : "Spain"},

    {questionText : "How many times did Finalnd qualify to EURO ?",
    option1 : "2 times",
    option2: "One time",
    option3 : "4 times",
    option4 : "6 times",
    correctAnswer : "One time"},
    {questionText : "How much is Bill gates wealth at the moment ?",
    option1 : "more then 100m",
    option2: "more than 1b",
    option3 : "more than 10b",
    option4 : "more than 100b",
    correctAnswer : "more than 100b"},
    {questionText : "When did algeria get its indepence ?",
    option1 : "1960",
    option2: "1962",
    option3 : "1970",
    option4 : "1980",
    correctAnswer : "1963"}

];